const ListDemoData = [
  {
    boardId: 1,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 2,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 3,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 4,
    title: '스터디룸 시간 제한 풀어주세요.',
    writer_name: '김수정4',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 5,
    title: '교내 취식 관련 문의드립니다.',
    writer_name: '김수정5',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 6,
    title: '학식 메뉴 건의합니다.',
    writer_name: '김수정6',
    likesCount: 12,
    isReplied: false,
    tag: '총학생회',
  },
  {
    boardId: 7,
    title: '대운동장 사용 시간 문의하고 싶어요.',
    writer_name: '김수정7',
    likesCount: 500,
    isReplied: true,
    tag: 'none',
  },
  {
    boardId: 8,
    title: '캠퍼스 간 교차수강 가능한가요?',
    writer_name: '김수정8',
    likesCount: 721,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 9,
    title: '셔틀버스 시간표 관련 문의드립니다.',
    writer_name: '김수정9',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 10,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 11,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 12,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 13,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 14,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 15,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 16,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 17,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 18,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 19,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 20,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 21,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 22,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 23,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 24,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 25,
    title: '스터디룸 시간 제한 풀어주세요.',
    writer_name: '김수정4',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 26,
    title: '교내 취식 관련 문의드립니다.',
    writer_name: '김수정5',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 27,
    title: '학식 메뉴 건의합니다.',
    writer_name: '김수정6',
    likesCount: 12,
    isReplied: false,
    tag: '총학생회',
  },
  {
    boardId: 28,
    title: '대운동장 사용 시간 문의하고 싶어요.',
    writer_name: '김수정7',
    likesCount: 500,
    isReplied: true,
    tag: 'none',
  },
  {
    boardId: 29,
    title: '캠퍼스 간 교차수강 가능한가요?',
    writer_name: '김수정8',
    likesCount: 721,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 30,
    title: '셔틀버스 시간표 관련 문의드립니다.',
    writer_name: '김수정9',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 31,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 32,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 33,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 34,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 35,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 36,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 37,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 38,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 39,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 40,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 41,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 42,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 43,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 44,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 45,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 46,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 47,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 48,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 49,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 50,
    title: '스터디룸 시간 제한 풀어주세요.',
    writer_name: '김수정4',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 51,
    title: '교내 취식 관련 문의드립니다.',
    writer_name: '김수정5',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 52,
    title: '학식 메뉴 건의합니다.',
    writer_name: '김수정6',
    likesCount: 12,
    isReplied: false,
    tag: '총학생회',
  },
  {
    boardId: 53,
    title: '대운동장 사용 시간 문의하고 싶어요.',
    writer_name: '김수정7',
    likesCount: 500,
    isReplied: true,
    tag: 'none',
  },
  {
    boardId: 54,
    title: '캠퍼스 간 교차수강 가능한가요?',
    writer_name: '김수정8',
    likesCount: 721,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 55,
    title: '셔틀버스 시간표 관련 문의드립니다.',
    writer_name: '김수정9',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 56,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
];

export default ListDemoData;
