const ListDemoData = [
  {
    boardId: 1,
    title: '안녕하세요. 시설 관련 건의 드립니다.',
    writer_name: '김수정',
    likesCount: 12,
    isReplied: true,
    tag: '총학생회',
  },
  {
    boardId: 2,
    title: '학생증 디자인 관련 요청드립니다.',
    writer_name: '김수정2',
    likesCount: 500,
    isReplied: false,
    tag: '자연캠',
  },
  {
    boardId: 3,
    title: '학교 휘장 설치해주세요.',
    writer_name: '김수정3',
    likesCount: 721,
    isReplied: true,
    tag: '자연캠',
  },
  {
    boardId: 4,
    title: '스터디룸 시간 제한 풀어주세요.',
    writer_name: '김수정4',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 5,
    title: '교내 취식 관련 문의드립니다.',
    writer_name: '김수정5',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
  {
    boardId: 6,
    title: '학식 메뉴 건의합니다.',
    writer_name: '김수정6',
    likesCount: 12,
    isReplied: false,
    tag: '총학생회',
  },
  {
    boardId: 7,
    title: '대운동장 사용 시간 문의하고 싶어요.',
    writer_name: '김수정7',
    likesCount: 500,
    isReplied: true,
    tag: 'none',
  },
  {
    boardId: 8,
    title: '캠퍼스 간 교차수강 가능한가요?',
    writer_name: '김수정8',
    likesCount: 721,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 9,
    title: '셔틀버스 시간표 관련 문의드립니다.',
    writer_name: '김수정9',
    likesCount: 3,
    isReplied: false,
    tag: 'none',
  },
  {
    boardId: 10,
    title: '도서관 열람실 자리 늘려주세요!',
    writer_name: '김수정10',
    likesCount: 17,
    isReplied: false,
    tag: '인문캠',
  },
];

export default ListDemoData;
